name: Docker Deployment Pipeline

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decrypt .env files
        run: |
          for f in */*/.env.gpg; do
            [ -f "$f" ] || continue
            out="${f%.gpg}"   # remove .gpg extension
            echo "Decrypting $f â†’ $out"
            gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" -o "$out" -d "$f"
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all services
        run: |
          docker compose build
          docker compose push

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy question-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/question-service:latest \
            --region asia-southeast1 \
            --allow-unauthenticated

          gcloud run deploy matching-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/matching-service:latest \
            --region asia-southeast1 \
            --allow-unauthenticated

          gcloud run deploy user-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest \
            --region asia-southeast1 \
            --allow-unauthenticated

          gcloud run deploy collaboration-service \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/collaboration-service:latest \
            --region asia-southeast1 \
            --allow-unauthenticated
